name: MonsterSnatcher
main: me.Fahlur.MonsterSnatcher.main
version: 1.0
description: Mob Capture Plugin
commands:
   MonsterSnatcher:
    usage: /<command>
    aliases: [ms]
    description: Main command returns version
