name: MonsterSnatcher
main: me.Fahlur.MonsterSnatcher.main
version: 1.0.5
author: Fahlur
description: Mob Capture Plugin
commands:
  monstersnatcher:
      description: Main command returns version
      aliases: [ms]
      usage: /<command>
permissions:
   ms.reload:
    description: Ability to use monsterSnatchers reload
   ms.catchable:
    description: Ability to use capture mobs
   ms.spawnerchanger:
    description: Ability to change spawners with spawn eggs
